/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as ExplorationRouteImport } from './routes/exploration'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkStudeoPaidAdsRouteImport } from './routes/work.studeo-paid-ads'
import { Route as WorkSlugRouteImport } from './routes/work.$slug'
import { Route as ExplorationVibeCodingRouteImport } from './routes/exploration_.vibe-coding'
import { Route as ExplorationPrintRouteImport } from './routes/exploration_.print'
import { Route as ExplorationMarketingRouteImport } from './routes/exploration_.marketing'
import { Route as Exploration3dRouteImport } from './routes/exploration_.3d'

const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorationRoute = ExplorationRouteImport.update({
  id: '/exploration',
  path: '/exploration',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkStudeoPaidAdsRoute = WorkStudeoPaidAdsRouteImport.update({
  id: '/work/studeo-paid-ads',
  path: '/work/studeo-paid-ads',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkSlugRoute = WorkSlugRouteImport.update({
  id: '/work/$slug',
  path: '/work/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorationVibeCodingRoute = ExplorationVibeCodingRouteImport.update({
  id: '/exploration_/vibe-coding',
  path: '/exploration/vibe-coding',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorationPrintRoute = ExplorationPrintRouteImport.update({
  id: '/exploration_/print',
  path: '/exploration/print',
  getParentRoute: () => rootRouteImport,
} as any)
const ExplorationMarketingRoute = ExplorationMarketingRouteImport.update({
  id: '/exploration_/marketing',
  path: '/exploration/marketing',
  getParentRoute: () => rootRouteImport,
} as any)
const Exploration3dRoute = Exploration3dRouteImport.update({
  id: '/exploration_/3d',
  path: '/exploration/3d',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exploration': typeof ExplorationRoute
  '/resume': typeof ResumeRoute
  '/exploration/3d': typeof Exploration3dRoute
  '/exploration/marketing': typeof ExplorationMarketingRoute
  '/exploration/print': typeof ExplorationPrintRoute
  '/exploration/vibe-coding': typeof ExplorationVibeCodingRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/studeo-paid-ads': typeof WorkStudeoPaidAdsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exploration': typeof ExplorationRoute
  '/resume': typeof ResumeRoute
  '/exploration/3d': typeof Exploration3dRoute
  '/exploration/marketing': typeof ExplorationMarketingRoute
  '/exploration/print': typeof ExplorationPrintRoute
  '/exploration/vibe-coding': typeof ExplorationVibeCodingRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/studeo-paid-ads': typeof WorkStudeoPaidAdsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/exploration': typeof ExplorationRoute
  '/resume': typeof ResumeRoute
  '/exploration_/3d': typeof Exploration3dRoute
  '/exploration_/marketing': typeof ExplorationMarketingRoute
  '/exploration_/print': typeof ExplorationPrintRoute
  '/exploration_/vibe-coding': typeof ExplorationVibeCodingRoute
  '/work/$slug': typeof WorkSlugRoute
  '/work/studeo-paid-ads': typeof WorkStudeoPaidAdsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/exploration'
    | '/resume'
    | '/exploration/3d'
    | '/exploration/marketing'
    | '/exploration/print'
    | '/exploration/vibe-coding'
    | '/work/$slug'
    | '/work/studeo-paid-ads'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/exploration'
    | '/resume'
    | '/exploration/3d'
    | '/exploration/marketing'
    | '/exploration/print'
    | '/exploration/vibe-coding'
    | '/work/$slug'
    | '/work/studeo-paid-ads'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/exploration'
    | '/resume'
    | '/exploration_/3d'
    | '/exploration_/marketing'
    | '/exploration_/print'
    | '/exploration_/vibe-coding'
    | '/work/$slug'
    | '/work/studeo-paid-ads'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  ExplorationRoute: typeof ExplorationRoute
  ResumeRoute: typeof ResumeRoute
  Exploration3dRoute: typeof Exploration3dRoute
  ExplorationMarketingRoute: typeof ExplorationMarketingRoute
  ExplorationPrintRoute: typeof ExplorationPrintRoute
  ExplorationVibeCodingRoute: typeof ExplorationVibeCodingRoute
  WorkSlugRoute: typeof WorkSlugRoute
  WorkStudeoPaidAdsRoute: typeof WorkStudeoPaidAdsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration': {
      id: '/exploration'
      path: '/exploration'
      fullPath: '/exploration'
      preLoaderRoute: typeof ExplorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/studeo-paid-ads': {
      id: '/work/studeo-paid-ads'
      path: '/work/studeo-paid-ads'
      fullPath: '/work/studeo-paid-ads'
      preLoaderRoute: typeof WorkStudeoPaidAdsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/work/$slug': {
      id: '/work/$slug'
      path: '/work/$slug'
      fullPath: '/work/$slug'
      preLoaderRoute: typeof WorkSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration_/vibe-coding': {
      id: '/exploration_/vibe-coding'
      path: '/exploration/vibe-coding'
      fullPath: '/exploration/vibe-coding'
      preLoaderRoute: typeof ExplorationVibeCodingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration_/print': {
      id: '/exploration_/print'
      path: '/exploration/print'
      fullPath: '/exploration/print'
      preLoaderRoute: typeof ExplorationPrintRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration_/marketing': {
      id: '/exploration_/marketing'
      path: '/exploration/marketing'
      fullPath: '/exploration/marketing'
      preLoaderRoute: typeof ExplorationMarketingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exploration_/3d': {
      id: '/exploration_/3d'
      path: '/exploration/3d'
      fullPath: '/exploration/3d'
      preLoaderRoute: typeof Exploration3dRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  ExplorationRoute: ExplorationRoute,
  ResumeRoute: ResumeRoute,
  Exploration3dRoute: Exploration3dRoute,
  ExplorationMarketingRoute: ExplorationMarketingRoute,
  ExplorationPrintRoute: ExplorationPrintRoute,
  ExplorationVibeCodingRoute: ExplorationVibeCodingRoute,
  WorkSlugRoute: WorkSlugRoute,
  WorkStudeoPaidAdsRoute: WorkStudeoPaidAdsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
